### ISSUE TITLE
Fix cors error on server for accessing the api in dev env

### ISSUE THREAD

**Issue by francoiscrouzet** [archaiodata/thacer#27]
## What we want

To have no cors errors when developping

## Why we want it

(Optional)

## How to implement and other infos

(Optional)

**Comment by AlZorba** [comment]
@francoiscrouzet après installation en local la version se heurte au CORS. J'ai regardé rapidement pour autoriser sur le serveur mais pour aller au plus simple j'ai fait un ticket. Wait 'n see

**Comment by francoiscrouzet** [comment]
> @francoiscrouzet après installation en local la version se heurte au CORS. J'ai regardé rapidement pour autoriser sur le serveur mais pour aller au plus simple j'ai fait un ticket. Wait 'n see

Oui c'est fait sur ma machine, mais bien sûr pas encore commité. C'est dans ma liste. Je n'ai pas vu ton ticket. En tout cas si c'est pressé dis moi c'est assez rapide à faire, ça marche deka

**Comment by francoiscrouzet** [comment]
We close, will be solved by https://github.com/archaiodata/thacer/issues/31
