### ISSUE TITLE
Change ceramic route to ceram, and redirect old url to new urls

### ISSUE THREAD

**Issue by francoiscrouzet** [archaiodata/thacer#43]
## What we want

1. change one route name
2. redirect url saved with all projects to the new one

## Why we want it

(Optional)

## How to implement and other infos

(Optional)

**Comment by francoiscrouzet** [comment]
@AlZorba la redirection automatique  de ceram.php vers ceram n'est finalement pas un quick win, mais un slow lose !
Je pense que quand le navigateur voit un .php, il cherche le fichier d'abord et dit non non, avant même de charger vue. 
Je ne sais pas si c'est possible de le faire marcher en front end, je n'ai absolument rien trouvé sur le sujet
Ca doit être possible de le faire marcher en backend, si ça te tente, je te laisse faire le ticket

**Comment by AlZorba** [comment]
@francoiscrouzet, je comprends. Pas de problème de mon coté pour ne pas implémenter ce routage dans Vue. Je verrais éventuellement pour le faire sur le serveur mais de toutes façon l'impacte est minime.
