### ISSUE TITLE
mapbox/leaflet : update version and/or install with tree shaking and/or load only in map page

### ISSUE THREAD

**Issue by francoiscrouzet** [archaiodata/thacer#58]
## What we want

It's in the title, we may see what's possible with mapbox/leaflet, any combination of what stands in the title could be nice

## Why we want it

(Optional)

## How to implement and other infos

This may help for loading in only one page (didn't read it) https://leighola.hashnode.dev/vue-mastery-the-smart-way-to-add-external-scripts-to-your-vue-app

**Comment by francoiscrouzet** [comment]
update to leaflet was made here: https://github.com/archaiodata/thacer/pull/105

**Comment by AlZorba** [comment]
Done by PR https://github.com/archaiodata/thacer/pull/105
